/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BusTicketingView;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.JButton;
import javax.swing.Timer;

/**
 *
 * @author pages coffie
 */
public class AdminControlPanel extends javax.swing.JFrame {

    /**
     * Creates new form InteractionForm
     */
    public AdminControlPanel() {
        initComponents();
        Timer timer = new Timer(1000, new ClockListener());
        timer.start();
    }
    class    ClockListener implements ActionListener{
        
        @Override
        public void actionPerformed(ActionEvent e) {
        Calendar calendar = Calendar.getInstance();
        int year  = calendar.get(Calendar.YEAR);
        int month  = calendar.get(Calendar.MONTH);
        int day  = calendar.get(Calendar.DATE);
        int hour  = calendar.get(Calendar.HOUR_OF_DAY);
        int minute  = calendar.get(Calendar.MINUTE);
        int sec  = calendar.get(Calendar.SECOND);
        timeLbl.setText("Date: "+year+"-" + month+1 + "-" + day + "  Time: "+ hour + ":"+ minute + ":" + sec);
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addBusBtn = new javax.swing.JButton();
        editBusBtn = new javax.swing.JButton();
        deleteBusBtn = new javax.swing.JButton();
        printBusBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        addRouteBtn = new javax.swing.JButton();
        editRouteBtn = new javax.swing.JButton();
        deleteRouteBtn = new javax.swing.JButton();
        printRouteBtn = new javax.swing.JButton();
        welcomeLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Control Panel");
        setLocation(new java.awt.Point(400, 200));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Bus Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell", 1, 14), new java.awt.Color(255, 0, 51))); // NOI18N

        addBusBtn.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        addBusBtn.setText("ADD");
        addBusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBusBtnActionPerformed(evt);
            }
        });

        editBusBtn.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        editBusBtn.setText("EDIT");

        deleteBusBtn.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        deleteBusBtn.setText("DELETE");

        printBusBtn.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        printBusBtn.setText("VIEW");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(deleteBusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(editBusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(addBusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(printBusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(addBusBtn)
                .addGap(18, 18, 18)
                .addComponent(editBusBtn)
                .addGap(26, 26, 26)
                .addComponent(deleteBusBtn)
                .addGap(27, 27, 27)
                .addComponent(printBusBtn)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Route Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell", 1, 14), new java.awt.Color(255, 0, 51))); // NOI18N

        addRouteBtn.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        addRouteBtn.setText("ADD");

        editRouteBtn.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        editRouteBtn.setText("EDIT");

        deleteRouteBtn.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        deleteRouteBtn.setText("DELETE");

        printRouteBtn.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        printRouteBtn.setText("VIEW");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editRouteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(addRouteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(deleteRouteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(printRouteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(addRouteBtn)
                .addGap(18, 18, 18)
                .addComponent(editRouteBtn)
                .addGap(29, 29, 29)
                .addComponent(deleteRouteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(printRouteBtn)
                .addGap(26, 26, 26))
        );

        welcomeLbl.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BusTicketingView/bus.jpg"))); // NOI18N

        timeLbl.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(timeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBusBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addBusBtnActionPerformed

    public void setWelcomeLbl(String name) {
        this.welcomeLbl.setText("Welcome " + name);
    }

    public JButton getAddBusBtn() {
        return addBusBtn;
    }

    public JButton getAddRouteBtn() {
        return addRouteBtn;
    }

    public JButton getDeleteBusBtn() {
        return deleteBusBtn;
    }

    public JButton getDeleteRouteBtn() {
        return deleteRouteBtn;
    }

    public JButton getEditBusBtn() {
        return editBusBtn;
    }

    public JButton getEditRouteBtn() {
        return editRouteBtn;
    }

    public JButton getPrintBusBtn() {
        return printBusBtn;
    }

    public JButton getPrintRouteBtn() {
        return printRouteBtn;
    }
    
    public void registerButtons(ActionListener ae){
    getAddBusBtn().addActionListener(ae);
    getAddRouteBtn().addActionListener(ae);
    getEditBusBtn().addActionListener(ae);
    getEditRouteBtn().addActionListener(ae);
    getDeleteBusBtn().addActionListener(ae);
    getDeleteRouteBtn().addActionListener(ae);
    getPrintBusBtn().addActionListener(ae);
    getPrintBusBtn().addActionListener(ae);
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminControlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBusBtn;
    private javax.swing.JButton addRouteBtn;
    private javax.swing.JButton deleteBusBtn;
    private javax.swing.JButton deleteRouteBtn;
    private javax.swing.JButton editBusBtn;
    private javax.swing.JButton editRouteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton printBusBtn;
    private javax.swing.JButton printRouteBtn;
    private javax.swing.JLabel timeLbl;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
